version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels: ["dependencies","github-actions","auto-merge"]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "09:00" }
    labels: ["dependencies","auto-merge"]
    versioning-strategy: auto
    groups: { rust-dependencies: { patterns: ["*"], update-types: ["minor","patch"] } }
  - package-ecosystem: "pip"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "09:00" }
    labels: ["dependencies","auto-merge"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule: { interval: "weekly", day: "monday", time: "09:00" }
    labels: ["dependencies","auto-merge"]